apiVersion: v1
kind: Namespace
metadata:
  name: training
  labels:
    app: player-churn-mlops
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: training-sa
  namespace: training
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-training-sa-role
